name: Checkout
on: [push]

jobs:
    checkout-action:
        runs-on: ubuntu-latest
        steps:
             - name: List Files Before
               run: ls -a
             - uses: actions/checkout@v4.1.1
             - name: List Files After
               run: ls -a
    checkout-and_disply-files:
        runs-on:  ubuntu-latest
        steps:
            - name: list
              run: ls -a
            - name: Checkout
              run: |
               git init
               git remote add origin "http://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github
               .com/$GITHUB_RRPOSITORY.git"
               git fetch origin
               git checkout main
            - name: List Files After
              run: ls -a




