name: Checkout
on: [push]

jobs:
    checkout-action:
        runs-on: ubunto-latest
        steps:
             - name: List Files Before
               run: ls -a
             - uses: actions/checkout@v4.1.1
             - name: List Files After
               run: ls -a
